### ISSUE TITLE
Nested forms support

### ISSUE THREAD

**Issue by borisrorsvort** [andypike/rectify#30]
Is there a way to easily handle nested attributes from has_many relationships?
Is it supported? if yes, do you have some gist we could use?

**Comment by andypike** [comment]
Hi @borisrorsvort,

Thanks for the interest in Rectify. I should add some more examples around this for sure. Maybe checkout issue https://github.com/andypike/rectify/issues/27 for another discussion.

Here's an example:

```ruby
class Blog < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :blog
end

class BlogForm < Rectify::Form
  attribute :title, String
  attribute :posts, Array[PostForm]
end

class PostForm < Rectify::Form
  attribute :title, String
  attribute :body, String
end

class PostsController < ApplicationController
  def new
    @form = BlogForm.new
  end

  def create
    @form = BlogForm.from_params(params)

    # You might want to put this in a command with a transaction, but I'll leave it here for simplicity
    if @form.valid?
        blog = Blog.create!(@form.attributes.slice(:title))
        @form.posts.each do |post|
          blog.posts.create!(post.attributes)
        end
    else
      render :new
    end
  end
end
```

I tend to favour a little more explicitness when dealing with forms in Rails as I seem to always get  caught out when using `accepts_nested_attributes_for` with complex forms and multiple contexts.

Does that help?

Thanks again for the question!!

💖

**Comment by bramj** [comment]
Hi @andypike,

If you don't use `accepts_nested_attributes_for` (which I agree can sure cause some pain), then you also don't use the `fields_for` helper? Because that would make
```ruby
@form = BlogForm.from_params(params)
```
fail because the posts would be in `params[:blog][:posts_attributes]` instead of `params[:blog][:posts]`.

Do you type out all your fields manually like `f.text_field 'posts[title]'` then?

**Comment by tombeynon** [comment]
@bramj Just to add my 2 cents - if you don't specify `accepts_nested_attributes_for` then `fields_for :posts` will use the `posts` param instead of `posts_attributes`. Should all work quite nicely. 

@andypike love this - much nicer than `accepts_nested_attributes_for`!

**Comment by bramj** [comment]
@tombeynon Hm, maybe I'm doing something wrong here, but that doesn't work for me. Basically `fields_for` doesn't want to work with an array.

Ended up with this ugly-looking-but-functional piece:
```ruby
- f.object.posts.each.with_index do |post, i|
  = f.fields_for "posts[#{i}]", post do |post_form|
    = post_form.text_field :title
    ...
```
If anyone has any cleaner suggestions, please do comment!

**Comment by nysthee** [comment]
I tend to use the object id as the key of the posts, ergo `"posts[#{post.id}]"`.
That way I can easily do:
`Post.update(params[:blog][:posts].keys, params[:blog][:posts].values)`

**Comment by tombeynon** [comment]
@bramj I'm on holiday so difficult to test, but I'd have thought the following would work. Note that your form object should *not* respond to `posts_attributes=` otherwise it will use that as the form key. 

```
f.fields_for :posts, f.object.posts do |pf|
  pf.text_field :name
end
```

@nysthee please be very careful doing that. If I changed the keys in the HTML of the form, i could update any object. Just make sure you're checking the user is allowed to change the provided ids.

**Comment by nysthee** [comment]
This was exemplary I would rather use the association to query/update the child-objects.
