### ISSUE TITLE
Tests failed onto MongoDB

### ISSUE THREAD

**Issue by CarefreeSlacker** [andypike/rectify#40]
Hello. I want to ask if **Rectify** compatible with MongoDB. Our ORM is mongoid. Test framework is Rspec. Into the development mode everything works fine, but all tests fail with error:
```
ActiveRecord::ConnectionNotEstablished:
  No connection pool for ActiveRecord::Base 
```
LInk to [stackoverflow](http://stackoverflow.com/questions/43653915/rectify-gem-mongo-tests-activerecordconnectionnotestablishedl)
Thank you for Awesome gem!

**Comment by andypike** [comment]
Hi @CarefreeSlacker,

Thanks for the question. I haven't done any work with MongoDB and so it isn't supported I'm afraid. Rectify currently uses ActiveRecord for the Query Objects and so that is a requirement at present. I guess you might be missing something from your `database.yml` file that is present in development but not in test. 

It's hard to say for sure, can you share your `database.yml` file here (obviously please don't include access details to any real database).

**Comment by CarefreeSlacker** [comment]
Thanks for fast response @andypike . I have included all necessary data into the stackoverflow question. MongoDB use **mongoid.yml** instead of **database.yml**. 
Looks like I have got answer - "MongoDB is probably not supported".
I will try to find solution. If I will find, I will make MR or write here the solution.
So I will not  close issue for a while.

**Comment by CarefreeSlacker** [comment]
I have examined source code and find out that some methods use ActiveRecord methods those does not supported by Mongoid.
For example ```Rectify::Command#transaction``` uses ```ActiveRecord::Base#transaction```, those is not supported by the Mongoid.
Or ```Rectify::Query#relation?``` checks ```cached_query.is_a?(ActiveRecord::Relation)``` but Mongoid query returns ```Mongoid::Criteria``` 
So i can definitely conclude that MongoDB is not supporting. 
I have wrote it just for feedback.
