### ISSUE TITLE
Configuring Date formats

### ISSUE THREAD

**Issue by tramuntanal** [andypike/rectify#48]
Hi,
I can't find if the format for parsing dates can be configured somewhere. I've checked the virtus gem but it also lacks this documentation and also seems abandoned.

Is it possible to force a given format when parsing dates? How do you adapt Form objects to parse dates in each locale format?

**Comment by deivid-rodriguez** [comment]
We figured this out, you can do it by using a custom virtus attribute and overriding / extending the `coerce` method! I think this can be closed!

**Comment by tramuntanal** [comment]
I still feel that rectify should naturally allow the configuration of a callback because multi locale software is very common, and it should support I18n in a more natural way.
Anyway, yes it is a great workaround, thank you @deivid-rodriguez !

**Comment by deivid-rodriguez** [comment]
No problem @tramuntanal!

I think maybe not _in_ rectify itself, but maybe a note in the README about virtus [custom coercions](https://github.com/solnic/virtus#custom-coercions) and how they can be used to localization would be great!

**Comment by tramuntanal** [comment]
Hi @deivid-rodriguez its one year since the project had its last commit and there are more than 25 PR pending, the author already said the he abandoned the project in favor of new ones with different perspective. I think it's not woth it as it won't be merged to master. Anyway I left a link to here from the Issue I also opened there.

**Comment by deivid-rodriguez** [comment]
I meant a PR to `rectify`. Ideally `rectify` will move away from `virtus` at some point... But in the mean time it's nice to get the current state well documented, it would've certainly saved us some time... :sweat_smile:.

I actually have a branch called `drectify` somewhere where I started the work on a `rectify` fork that uses the `dry-*` family instead of `virtus`, I should fine time to work on it a bit more...
